resolver: lts-12.19

packages:
  - apecs
  - apecs-physics
  - apecs-physics-gloss
# - apecs-stm            disabled until stm-containers gets into stackage
  - examples

nix:
  pure: false
  packages:
    - libGL
    - freeglut
    - mesa_glu
    - zlib
