resolver: lts-9.11
packages:
- .
- location:
    git: git@github.com:jonascarpay/apecs
    commit: 7ee9c5dc415fe1d7e9eb32c5673f95a8c36aa9aa
  extra-dep: true
extra-deps:
flags: {}
extra-package-dbs: []
